version: 2
jobs:
  test-locally:
    docker:
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install .

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
  push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t us.gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:$CIRCLE_SHA1 -t us.gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:latest .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: gcloud docker -- push us.gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE_NAME}:$CIRCLE_SHA1
workflows:
  version: 2
  test-and-build-image:
    jobs:
      - test-locally
      - push-image:
          requires:
            - test-locally
